parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
  project:
    - 'tsconfig.json'
    - 'tsconfig.sw.json'
  sourceType: module
  tsconfigRootDir: '.'

extends:
  - plugin:prettier/recommended
  - plugin:react/recommended
  - prettier/react

plugins:
  - "@typescript-eslint"
  - react-hooks
  - prettier

rules:
  react/display-name: off
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"

settings:
  react:
    version: "detect"
