parser: "@typescript-eslint/parser"

parserOptions:
  project: 'tsconfig.json'
  tsconfigRootDir: '.'

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:react-app/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - prettier/react

plugins:
  - "@typescript-eslint"
  - prettier

rules:
  react-app/jsx-a11y/accessible-emoji: off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-non-null-assertion": off
