image: node:alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run build
  only:
    - tags
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  environment:
    name: production
    url: https://iiro.fi
  before_script:
    - npm i -g netlify-cli@next
  script:
    - netlify deploy -d public --prod
  only:
    - tags
