stages:
  - build
  - deploy

clone:
  stage: build
  script:
    - git clone git@gitlab.com:iiroj/iiro.fi.git .

build:
  stage: build
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  script:
    - cp build/* /var/www/iiro.fi/
