image: node:alpine

stages:
  - install
  - build
  - deploy

# Pull cached dependencies by default
cache:
  key: $CI_PIPELINE_ID
  paths:
    - node_modules/
  policy: pull

# Install dependencies in CI mode
Install:
  stage: install
  script:
    - npm ci
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - node_modules/

# Audit dependencies
Audit:
  stage: build
  script:
    - npm audit

# Lint code
Lint:
  stage: build
  script:
    - npm run lint

# Build static site
Build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - public/

# Deploy master
Deploy:
  stage: deploy
  image: cgswong/aws:latest
  cache: {} # Cache not needed for Deploy job
  environment:
    name: production
    url: https://iiro.fi
  script:
    - aws s3 sync ./public s3://${AWS_S3_BUCKET_NAME}/ --delete --exclude "*"
        --include "*.html"
        --cache-control max-age=0,no-cache-no-store,must-revalidate
    - aws s3 sync ./public s3://${AWS_S3_BUCKET_NAME}/ --delete --exclude "*"
        --include "*.jpg"
        --include "*.png"
        --include "*.ico"
        --cache-control public,max-age=2592000
    - aws s3 sync ./public s3://${AWS_S3_BUCKET_NAME}/ --delete --exclude "*"
        --include "*.js"
        --include "*.map"
        --cache-control public,immutable,max-age=31536000
    - aws cloudfront create-invalidation
        --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID
        --paths "/*"
  only:
    - master
