image: node:alpine

stages:
  - build
  - deploy

Build:
  stage: build
  except:
    - tags
  script:
    - npm install
    - npm run lint
    - npm run build
  cache:
    key: node_modules
    paths:
      - node_modules/
  artifacts:
    paths:
      - lambda/
      - public/

Audit:
  stage: build
  except:
    - tags
  script:
    - npm audit

Deploy:
  stage: deploy
  environment:
    name: production
    url: https://iiro.fi
  before_script:
    - npm install -g netlify-cli
  script:
    - netlify deploy
      --prod
      --dir public
      --functions lambda
      --message "$CI_COMMIT_TITLE"
  only:
    - master
