stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install
    - mkdir -p build
    - npm run build
    - rm -fr /var/www/iiro.fi/*
    - cp build/* /var/www/iiro.fi/
  cache:
    paths:
      - node_modules
    key: "$CI_BUILD_REF"
    untracked: true
