image: node:alpine

stages:
  - install
  - test
  - build
  - deploy

"Install":
  stage: install
  script:
    - npm ci
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
  cache:
    paths:
      - node_modules

"Lint":
  stage: test
  script:
    - npm run lint

"Build Site":
  stage: build
  script:
    - npm run build:site
  artifacts:
    paths:
      - public

"Build Lambda":
  stage: build
  script:
    - npm run build:lambda
  artifacts:
    paths:
      - lambda

"Netlify":
  stage: deploy
  environment:
    name: production
    url: https://iiro.fi
  before_script:
    - npm i -g netlify-cli@next
  script:
    - netlify deploy -d public -f lambda --prod
  only:
    - tags
