stages:
  - install
  - build
  - deploy

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - node_modules
    - build

install:
  stage: install
  environment: Production
  script:
    - npm install

build:
  stage: build
  environment: Production
  script:
    - rm -frv build/*
    - mkdir -p build
    - npm run build

deploy:
  stage: deploy
  environment: Production
  script:
    - rm -frv /var/www/iiro.fi/*
    - cp build/* /var/www/iiro.fi/