image: node:alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run build
  only:
    - master
  cache:
    key: node_modules
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  environment:
    name: production
    url: https://iiro.fi
  before_script:
    - npm i -g @static/discharge
  script:
    - discharge deploy
    - discharge distribute
  only:
    - master
