image: node:alpine

stages:
  - install
  - build
  - deploy

# Pull cached dependencies by default
cache:
  key: $CI_PIPELINE_ID
  paths:
    - node_modules/
  policy: pull

# Install dependencies in CI mode
Install:
  stage: install
  except:
    - tags
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - node_modules/
  script:
    - npm ci

# Audit dependencies
Audit:
  stage: build
  except:
    - tags
  script:
    - npm audit

# Lint code
Lint:
  stage: build
  except:
    - tags
  script:
    - npm run lint

# Build static site
Build:
  stage: build
  except:
    - tags
  script:
    - npm run build
  artifacts:
    paths:
      - public/

# Deploy master
Deploy:
  stage: deploy
  environment:
    name: production
    url: https://iiro.fi
  cache: {}
  before_script:
    - npm install -g netlify-cli
  script:
    - netlify deploy
      --prod
      --dir public
      --functions lambda
      --message "$CI_COMMIT_TITLE"
  only:
    - master
