stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install
    - mkdir -p build
    - npm run build
    - cp build/* /var/www/iiro.fi/
  cache:
    paths:
      - node_modules/
      - build/
    key: "$CI_BUILD_NAME"
    untracked: true
