image: node:alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run build
  only:
    - master
  cache:
    key: node_modules
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: cgswong/aws:latest
  environment:
    name: production
    url: https://iiro.fi
  script:
    - aws s3 sync ./build s3://${AWS_S3_BUCKET_NAME}/ --delete --exclude "*"
        --include "*.html"
        --cache-control max-age=0,no-cache-no-store,must-revalidate
    - aws s3 sync ./build s3://${AWS_S3_BUCKET_NAME}/ --delete --exclude "*"
        --include "*.jpg"
        --include "*.png"
        --include "*.ico"
        --cache-control public,max-age=2592000
    - aws s3 sync ./build s3://${AWS_S3_BUCKET_NAME}/ --delete --exclude "*"
        --include "*.js"
        --include "*.map"
        --cache-control public,immutable,max-age=31536000
    - aws cloudfront create-invalidation
        --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID
        --paths "/*"
  only:
    - master
