stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - mkdir -p build
    - npm run build
  cache:
    paths:
      - build/

deploy:
  stage: deploy
  script:
    - cp ./build/* /var/www/iiro.fi/
