language: node_js

node_js:
  - lts/*

cache:
  directories:
  - node_modules

before_script:
  - npm install

script:
  - npm run lint
  - npm run build

deploy:
  - provider: script
    on:
      tags: true
    skip_cleanup: true
    script:
      - npm install -g netlify-cli
      - netlify deploy -p -d public -f lambda -m "$TRAVIS_TAG"
