[build]
  command = "npm run build"
  publish = "public"
  functions = "lambda"

[[redirects]]
  from = "https://iiro.jappinen.fi/*"
  to   = "https://iiro.fi/:splat"

[[redirects]]
  from = "https://iiro.xn--jppinen-5wa.fi/*"
  to   = "https://iiro.fi/:splat"
