[build]
  publish = "public"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=0,no-cache,no-store,must-revalidate"
    Content-Security-Policy = "default-src 'none'; connect-src 'self' https://fonts.gstatic.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com"
    Link = "<https://fonts.googleapis.com/css?family=IBM+Plex+Sans+Condensed:400,600|IBM+Plex+Serif:300> rel=\"preload\" as=\"style\" crossorigin=\"anonymous\""
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public,max-age=2592000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public,max-age=2592000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public,max-age=2592000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public,max-age=2592000"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Cache-Control = "public,max-age=2592000"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public,immutable,max-age=31536000"
