[build]
  command = "npm run build"
  publish = "build/site"
  functions = "build/lambda"

[[headers]]
  for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data:; connect-src 'self' https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"
      Referrer-Policy = "origin-when-cross-origin"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"

  for = "/sw.js"
    [headers.values]
      Cache-Control = "no-cache, no-store, must-revalidate"
      Pragma = "no-cache"
      Expires = "0"

[[redirects]]
  from = "https://iiro.jappinen.fi/*"
  to = "https://iiro.fi/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://iiro.xn--jppinen-5wa.fi/*"
  to = "https://iiro.fi/:splat"
  status = 301
  force = true
