name = "iiro-dev"

workers_dev = false
compatibility_date = "2023-02-21"

main = "./build/index.js"

[site]
bucket = "./public"

[build]
command = "npm run build"

[vars]
CF_BEACON_TOKEN = ""

[env.production]
name = "iiro"

[env.production.vars]
CF_BEACON_TOKEN = "c7794cb559534b8d894864b0398f9f7f"
