name = "iiro_fi"
type = "javascript"
workers_dev = false
# account_id = $CF_ACCOUNT_ID
# zone_id = $CF_ZONE_ID
route = "iiro.fi/*"

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm ci && npm run build"
cwd = "workers-site"

[build.upload]
  format  = "service-worker"
