name = "iiro-dev"

workers_dev = true
compatibility_date = "2023-01-21"
compatibility_flags = ["streams_enable_constructors"]

main = "./build/index.js"

[site]
bucket = "./public"

[build]
command = "npm run build"

[vars]
CF_BEACON_TOKEN = ""

[env.production]
name = "iiro"

[env.production.vars]
CF_BEACON_TOKEN = "c7794cb559534b8d894864b0398f9f7f"
