compatibility_date = "2021-09-17"

name = "iiro_fi"
type = "javascript"
workers_dev = false
# account_id = $CF_ACCOUNT_ID
# zone_id = $CF_ZONE_ID
route = "iiro.fi/*"

[site]
bucket = "./site/dist"
entry-point = "worker"

[build]
command = "exit 0"

[build.upload]
  format  = "service-worker"
