name = "iiro"

workers_dev = true
compatibility_date = "2022-11-13"
compatibility_flags = ["streams_enable_constructors"]

main = "./build/index.js"

[site]
bucket = "./public"

[build]
command = "npm run build"
