name: Statichost.eu

on:
  push:
    branches: [main]
  workflow_dispatch:

enable-email-notifications: true

concurrency:
  group: "statichost.eu"
  cancel-in-progress: false

jobs:
  Deploy:
    runs-on: codeberg-tiny
    steps:
      - name: Checkout repository
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Bun
        uses: ./.forgejo/actions/setup-bun

      - name: Restore Bun cache
        uses: https://data.forgejo.org/actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: cache
        with:
          path: ~/.bun/install/cache
          key: ${{ hashFiles('bun.lock') }}

      - name: Bun install
        run: bun install --frozen-lockfile

      - name: Save Bun cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: https://data.forgejo.org/actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.bun/install/cache
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: bun run build

      - name: Zip
        run: |
          cd public
          zip -qr "statichost.zip" .

      - name: Drop
        run: |
          curl --silent --fail-with-body \
            -X POST "https://builder.statichost.eu/iiro/drop" \
            -H "Authorization: Bearer $STATICHOST_APIKEY" \
            -H "Content-Type: application/zip" \
            -H "Accept: text/plain" \
            --data-binary "@public/statichost.zip"
        env:
          STATICHOST_APIKEY: ${{ secrets.STATICHOST_APIKEY }}
