name: Statichost.eu

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

enable-email-notifications: true

concurrency:
  group: "statichost.eu"
  cancel-in-progress: false

jobs:
  Build:
    runs-on: codeberg-small
    outputs:
      artifact-url: ${{ steps.artifact.outputs.artifact-url }}
    steps:
      - name: Checkout repository
        # https://code.forgejo.org/actions/checkout/commit/de0fac2e4500dabe0009e67214ff5f5447ce83dd
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node.js
        # https://code.forgejo.org/actions/setup-node/commit/48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        uses: https://data.forgejo.org/actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: ".node-version"
          package-manager-cache: false

      - name: Restore npm cache
        # https://code.forgejo.org/actions/cache/commit/27d5ce7f107fe9357f9df03efb73ab90386fccae
        uses: https://data.forgejo.org/actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae
        id: npm-cache
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Run npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Save npm cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        # https://code.forgejo.org/actions/cache/commit/27d5ce7f107fe9357f9df03efb73ab90386fccae
        uses: https://data.forgejo.org/actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: node_modules
          key: ${{ steps.npm-cache.outputs.cache-primary-key }}

      - name: Build
        run: npm run build

      - name: Upload artifact
        id: artifact
        # https://code.forgejo.org/forgejo/upload-artifact/commit/16871d9e8cfcf27ff31822cac382bbb5450f1e1e
        uses: https://data.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e
        with:
          name: statichost
          path: public
          retention-days: 1

  Deploy:
    if: ${{ forgejo.event_name == 'push' && forgejo.ref_name == 'main' }}
    needs: Build
    runs-on: codeberg-tiny
    steps:
      - name: Download artifact
        run: |
          curl --silent ${{ needs.Build.outputs.artifact-url }} \
            -H "Authorization: Bearer $FORGEJO_TOKEN" \
            -o statichost.zip

      - name: Drop
        run: |
          curl --silent --fail-with-body \
            -X POST "https://builder.statichost.eu/iiro/drop" \
            -H "Authorization: Bearer $STATICHOST_APIKEY" \
            -H "Content-Type: application/zip" \
            -H "Accept: text/plain" \
            --data-binary "@statichost.zip"
        env:
          STATICHOST_APIKEY: ${{ secrets.STATICHOST_APIKEY }}
