name: Setup OpenTofu

runs:
  using: composite
  steps:
    - uses: ./.forgejo/actions/setup-binary
      with:
        bin: /usr/local/bin/tofu
        checksum: 68026be376f8910a318645acc65f21da8b39ab86946cb0dd6cd16ef1705f34b3
        url: https://github.com/opentofu/opentofu/releases/download/v1.11.6/tofu_1.11.6_linux_amd64.zip
        archive: tofu_1.11.6_linux_amd64.zip
        extracted-bin: tofu
