when:
  - event: ["push", "manual"]
    branch: ["main"]

engine: "microvm"
image: "nixos"
dependencies:
  - nodejs_26
  - curl

steps:
  - name: "Install dependencies"
    command: "npm ci"
  - name: "Build"
    command: "npm run build"
  - name: "Deploy"
    command: "npm run deploy"
