name: Setup Bun

runs:
  using: composite
  steps:
    - uses: ./.forgejo/actions/setup-binary
      with:
        bin: /usr/local/bin/bun
        checksum: 79c0771fa8b92c33aae41e15a0e0d307ea99d0e2f00317c71c6c53237a78e25a
        url: https://github.com/oven-sh/bun/releases/download/bun-v1.3.13/bun-linux-x64.zip
        archive: bun-linux-x64.zip
        extracted-bin: bun-linux-x64/bun
