name: Setup Bun

inputs:
  bin:
    default: /usr/local/bin/bun
  checksum:
    default: 79c0771fa8b92c33aae41e15a0e0d307ea99d0e2f00317c71c6c53237a78e25a
  url:
    default: https://github.com/oven-sh/bun/releases/download/bun-v1.3.13/bun-linux-x64.zip
  archive:
    default: bun-linux-x64.zip
  extracted-bin:
    default: bun-linux-x64/bun

runs:
  using: composite
  steps:
    - name: Restore cached binary
      uses: https://data.forgejo.org/actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      id: cache
      with:
        path: ${{ inputs.bin }}
        key: cached-${{ inputs.bin }}-${{ inputs.checksum }}

    - name: Download binary
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "$(mktemp -d)"
        curl -fsSLO "${{ inputs.url }}"
        echo "${{ inputs.checksum }}  ${{ inputs.archive }}" | sha256sum -c -
        unzip -q "${{ inputs.archive }}"
        mv "${{ inputs.extracted-bin }}" "${{ inputs.bin }}"
        chmod +x "${{ inputs.bin }}"

    - name: Cache downloaded binary
      if: steps.cache.outputs.cache-hit != 'true'
      uses: https://data.forgejo.org/actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ inputs.bin }}
        key: ${{ steps.cache.outputs.cache-primary-key }}

    - name: Print binary version
      shell: bash
      run: ${{ inputs.bin }} --version
