name: Bunny.net

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "opentofu"
  cancel-in-progress: false

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: Bunny.net
      url: https://iiro.fi
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.bun/install/cache
          key: ${{ hashFiles('bun.lock') }}
      - run: bun install --frozen-lockfile
      - run: bun run build
      - uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2.0.0
      - run: tofu init
        working-directory: infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUNNYNET_API_KEY: ${{ secrets.BUNNYNET_API_KEY }}
      - run: tofu apply -auto-approve
        working-directory: infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUNNYNET_API_KEY: ${{ secrets.BUNNYNET_API_KEY }}
