name: Statichost.eu

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "statichost.eu"
  cancel-in-progress: false

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      artifact-url: ${{ steps.artifact.outputs.artifact-url }}
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout/commit/3d3c42e5aac5ba805825da76410c181273ba90b1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Node.js
        # https://github.com/actions/setup-node/commit/820762786026740c76f36085b0efc47a31fe5020
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: ".node-version"
          package-manager-cache: false

      - name: Restore npm cache
        # https://github.com/actions/cache/commit/55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        id: npm-cache
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Run npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Save npm cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        # https://github.com/actions/cache/commit/55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: node_modules
          key: ${{ steps.npm-cache.outputs.cache-primary-key }}

      - name: Build
        run: npm run build

      - name: Upload artifact
        id: artifact
        # https://github.com/actions/upload-artifact/commit/043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: statichost
          path: public
          retention-days: 1

  Deploy:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: Build
    runs-on: ubuntu-latest
    environment:
      name: Statichost.eu
      url: https://iiro.fi
    steps:
      - name: Download artifact
        # https://github.com/actions/download-artifact/commit/3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          skip-decompress: true

      - name: Drop
        run: |
          curl --silent --fail-with-body \
            -X POST "https://builder.statichost.eu/iiro/drop" \
            -H "Authorization: Bearer $STATICHOST_APIKEY" \
            -H "Content-Type: application/zip" \
            -H "Accept: text/plain" \
            --data-binary "@statichost.zip"
        env:
          STATICHOST_APIKEY: ${{ secrets.STATICHOST_APIKEY }}
