name: Pull Request

on:
  pull_request:

jobs:
  Preview:
    environment:
      name: Preview
      url: ${{ steps.deployment.outputs.deployment-url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: actions/cache@v4
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
      - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - run: npm run lint
      - name: Get current git commit
        id: git-commit
        run: |
          echo "SHA_SHORT=$(git show -s --format=%h)" >> "$GITHUB_OUTPUT"
          echo "MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
      - id: deployment
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: versions upload --tag "${{ steps.git-commit.outputs.SHA_SHORT }}" --message "${{ steps.git-commit.outputs.MESSAGE }}"
