name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Shared:
    uses: ./.github/workflows/install-lint.yml

  Preview:
    if: ${{ github.event_name == 'pull_request' }}
    needs:
      - Shared
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iiroj/pages-action@branch-deployment-status
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: iiro
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
