name: Create GitHub Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    name: GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout/commit/9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Create GitHub release
        uses: ./.github/actions/github-release
        with:
          git-tag: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
