name: Release

on:
  push:
    # Semver-like tags "v1.0.0"
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

concurrency: production_deployment

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iiroj/pages-action@branch-deployment-status
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: iiro
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
